# -*- coding: utf-8 -*-
"""inventory_planner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-P_eHYzM91dYIhFXq3GzEsrMhZJjZHV

**Q1**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ingredient_class.py
# 
# class InsufficientStockError(Exception):
#     """Raised when inventory quantity is too low for a recipe."""
#     pass
# 
# 
# class Ingredient:
#     """Represents a single item in the kitchen inventory."""
# 
#     def __init__(self, name, quantity, unit):
#         try:
#             self.quantity = float(quantity)
#         except (TypeError, ValueError):
#             raise ValueError("Quantity must be numeric.") from None
# 
#         self.name = name
#         self.unit = unit
# 
#     def to_csv_row(self):
#         """Converts the Ingredient object to a list for CSV writing."""
#         return [self.name, self.quantity, self.unit]
# 
#     def __str__(self):
#         """Nice representation for display."""
#         return f"{self.name}: {self.quantity} {self.unit}"
# 
# 
# 
# RECIPES = {
#     "Pap and Wors": {
#         "Maize Meal": 250,
#         "Wors": 500
#     },
#     "Spinach and Feta Salad": {
#         "Spinach": 100,
#         "Feta": 50,
#         "Tomato": 1
#     },
# 
#     "Chicken Wrap": {
#     "Chicken": 150,
#     "Tortilla Wrap": 1,
#     "Carrot": 30,
#     "Green Pepper": 30,
#     "Onion": 20,
#     "Lettuce": 40,
#     "Sauce": 20
# }
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile inventory_planner.py
# 
# import csv
# from ingredient_class import Ingredient
# 
# def save_inventory(inventory):
#     """Saves the current inventory to a CSV file."""
#     with open('inventory.csv', 'w', newline='') as csvfile:
#         writer = csv.writer(csvfile)
#         writer.writerow(["name", "quantity", "unit"])
#         for ingredient in inventory:
#             writer.writerow(ingredient.to_csv_row())
# 
# def load_inventory():
#     """Loads inventory from a CSV file and returns a list of Ingredient objects."""
#     inventory_map = {}
#     try:
#         with open('inventory.csv', 'r', newline='') as csvfile:
#             reader = csv.reader(csvfile)
#             headers = next(reader)
#             if headers != ["name", "quantity", "unit"]:
#                 raise ValueError("Invalid CSV header. Expected ['name', 'quantity', 'unit'].")
# 
#             for row in reader:
#                 if len(row) != 3:
#                     print(f"Skipping malformed row: {row}")
#                     continue
#                 name, quantity_str, unit = row
#                 try:
#                     quantity = float(quantity_str)
#                     if name in inventory_map:
# 
#                         inventory_map[name].quantity += quantity
#                     else:
#                         inventory_map[name] = Ingredient(name, quantity, unit)
#                 except ValueError:
#                     print(f"Skipping row due to invalid quantity for {name}: '{quantity_str}' is not numeric.")
#     except FileNotFoundError:
#         print("inventory.csv not found. Returning empty inventory.")
#         return []
#     except ValueError as e:
#         print(f"Error loading inventory: {e}")
#         return []
# 
#     return list(inventory_map.values())

import csv
from ingredient_class import Ingredient, InsufficientStockError, RECIPES

INVENTORY_FILE = 'inventory.csv'
HEADER = ['Name', 'Quantity', 'Unit']


def load_inventory():
    """
    Loads ingredients from the CSV file.

    Returns:
      list[Ingredient].
    Notes:
      Warn on missing/extra headers; merge duplicates by (name, unit).
    """
    inventory = []

    try:
        with open(INVENTORY_FILE, mode="r", newline="", encoding="utf-8") as f:
            reader = csv.reader(f)


            try:
                header_row = next(reader)
            except StopIteration:

                return []


            header_map = {col.strip(): idx for idx, col in enumerate(header_row)}


            missing = [col for col in HEADER if col not in header_map]
            extra = [col for col in header_row if col not in HEADER]

            if missing:
                print(f"Warning: Missing expected column(s) in {INVENTORY_FILE}: {', '.join(missing)}")
            if extra:
                print(f"Warning: Unexpected column(s) in {INVENTORY_FILE}: {', '.join(extra)}")


            if any(col not in header_map for col in ['Name', 'Quantity', 'Unit']):
                print("Warning: Required columns are missing. Returning empty inventory.")
                return []

            name_idx = header_map['Name']
            qty_idx = header_map['Quantity']
            unit_idx = header_map['Unit']


            merged = {}

            for row in reader:

                if not row or all(str(cell).strip() == "" for cell in row):
                    continue

                try:
                    name = row[name_idx].strip()
                    quantity_raw = row[qty_idx]
                    unit = row[unit_idx].strip()
                except IndexError:
                    print(f"Warning: Skipping malformed row in {INVENTORY_FILE}: {row}")
                    continue

                if not name:
                    print(f"Warning: Skipping row with empty Name in {INVENTORY_FILE}: {row}")
                    continue

                try:
                    ingredient = Ingredient(name, quantity_raw, unit)
                except ValueError as e:

                    print(f"Warning: Skipping row with invalid quantity for '{name}': {e}")
                    continue

                key = (name.lower(), unit.lower())
                if key in merged:

                    merged[key].quantity += ingredient.quantity
                else:
                    merged[key] = ingredient

            inventory = list(merged.values())

    except FileNotFoundError:
        print(f"Warning: {INVENTORY_FILE} not found. Starting with empty inventory.")
        return []

    return inventory


def save_inventory(inventory):
    """
    Saves the current inventory to CSV.

    Args:
      inventory: list[Ingredient] to persist (one row per item via to_csv_row()).
    """
    with open(INVENTORY_FILE, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(HEADER)

        for item in inventory:
            writer.writerow(item.to_csv_row())

"""Q2"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile inventory_planner.py
# 
# import csv
# from ingredient_class import Ingredient
# 
# def save_inventory(inventory):
#     """Saves the current inventory to a CSV file."""
#     with open('inventory.csv', 'w', newline='') as csvfile:
#         writer = csv.writer(csvfile)
#         writer.writerow(["name", "quantity", "unit"])
#         for ingredient in inventory:
#             writer.writerow(ingredient.to_csv_row())
# 
# def load_inventory():
#     """Loads inventory from a CSV file and returns a list of Ingredient objects."""
#     inventory_map = {}
#     try:
#         with open('inventory.csv', 'r', newline='') as csvfile:
#             reader = csv.reader(csvfile)
#             headers = next(reader)
#             if headers != ["name", "quantity", "unit"]:
#                 raise ValueError("Invalid CSV header. Expected ['name', 'quantity', 'unit'].")
# 
#             for row in reader:
#                 if len(row) != 3:
#                     print(f"Skipping malformed row: {row}")
#                     continue
#                 name, quantity_str, unit = row
#                 try:
#                     quantity = float(quantity_str)
#                     if name in inventory_map:
#                         inventory_map[name].quantity += quantity
#                     else:
#                         inventory_map[name] = Ingredient(name, quantity, unit)
#                 except ValueError:
#                     print(f"Skipping row due to invalid quantity for {name}: '{quantity_str}' is not numeric.")
#     except FileNotFoundError:
#         print("inventory.csv not found. Returning empty inventory.")
#         return []
#     except ValueError as e:
#         print(f"Error loading inventory: {e}")
#         return []
# 
#     return list(inventory_map.values())
# 
# def view_inventory(inventory):
#     """Displays the current inventory."""
#     if not inventory:
#         print("Your inventory is currently empty.")
#         return
# 
#     print("\n--- Current Inventory ---")
#     for ingredient in inventory:
#         print(ingredient)
#     print("-------------------------")
# 
# def add_ingredient(inventory):
#     """Adds a new ingredient or updates an existing one in the inventory."""
#     print("\n--- Add/Update Ingredient ---")
#     while True:
#         name = input("Enter ingredient name (e.g., 'Flour', 'Sugar'): ").strip()
#         if name:
#             break
#         else:
#             print("Ingredient name cannot be empty. Please try again.")
# 
#     while True:
#         unit = input(f"Enter unit for {name} (e.g., 'grams', 'ml', 'pieces'): ").strip()
#         if unit:
#             break
#         else:
#             print("Unit cannot be empty. Please try again.")
# 
#     while True:
#         quantity_str = input(f"Enter quantity for {name} in {unit}: ").strip()
#         try:
#             quantity = float(quantity_str)
#             if quantity <= 0:
#                 print("Quantity must be a positive number. Please try again.")
#             else:
#                 break
#         except ValueError:
#             print("Invalid quantity. Please enter a numeric value.")
# 
#     found_existing = False
#     for item in inventory:
#         if item.name.lower() == name.lower():
#             item.quantity += quantity
# 
#             if item.unit.lower() != unit.lower():
#                 print(f"Warning: Unit for '{name}' changed from '{item.unit}' to '{unit}'.")
#                 item.unit = unit
#             print(f"Updated quantity for {item.name}: new total is {item.quantity} {item.unit}.")
#             found_existing = True
#             break
# 
#     if not found_existing:
#         new_ingredient = Ingredient(name, quantity, unit)
#         inventory.append(new_ingredient)
#         print(f"Added new ingredient: {new_ingredient}.")
#     print("-----------------------------")

"""Q3"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile inventory_planner.py
# import csv
# from ingredient_class import Ingredient, InsufficientStockError, RECIPES
# 
# 
# def save_inventory(inventory):
#     """Saves the current inventory to a CSV file."""
#     with open('inventory.csv', 'w', newline='') as csvfile:
#         writer = csv.writer(csvfile)
#         writer.writerow(["name", "quantity", "unit"])
#         for ingredient in inventory:
#             writer.writerow(ingredient.to_csv_row())
# 
# 
# def load_inventory():
#     """Loads inventory from a CSV file and returns a list of Ingredient objects.
# 
#     - Validates the CSV header.
#     - Merges duplicate ingredients by name (case-sensitive key).
#     """
#     inventory_map = {}
#     try:
#         with open('inventory.csv', 'r', newline='') as csvfile:
#             reader = csv.reader(csvfile)
#             headers = next(reader)
#             if headers != ["name", "quantity", "unit"]:
#                 raise ValueError(
#                     "Invalid CSV header. Expected ['name', 'quantity', 'unit']."
#                 )
# 
#             for row in reader:
#                 if len(row) != 3:
#                     print(f"Skipping malformed row: {row}")
#                     continue
#                 name, quantity_str, unit = row
#                 try:
#                     quantity = float(quantity_str)
#                     if name in inventory_map:
#                         inventory_map[name].quantity += quantity
#                     else:
#                         inventory_map[name] = Ingredient(name, quantity, unit)
#                 except ValueError:
#                     print(
#                         f"Skipping row due to invalid quantity for {name}: "
#                         f"'{quantity_str}' is not numeric."
#                     )
#     except FileNotFoundError:
#         print("inventory.csv not found. Returning empty inventory.")
#         return []
#     except ValueError as e:
#         print(f"Error loading inventory: {e}")
#         return []
# 
#     return list(inventory_map.values())
# 
# 
# def view_inventory(inventory):
#     """Displays the current inventory."""
#     if not inventory:
#         print("Your inventory is currently empty.")
#         return
# 
#     print("\n--- Current Inventory ---")
#     for ingredient in inventory:
#         print(ingredient)
#     print("-------------------------")
# 
# 
# def add_ingredient(inventory):
#     """Adds a new ingredient or updates an existing one in the inventory."""
#     print("\n--- Add/Update Ingredient ---")
#     while True:
#         name = input("Enter ingredient name (e.g., 'Flour', 'Sugar'): ").strip()
#         if name:
#             break
#         else:
#             print("Ingredient name cannot be empty. Please try again.")
# 
#     while True:
#         unit = input(
#             f"Enter unit for {name} (e.g., 'grams', 'ml', 'pieces'): "
#         ).strip()
#         if unit:
#             break
#         else:
#             print("Unit cannot be empty. Please try again.")
# 
#     while True:
#         quantity_str = input(f"Enter quantity for {name} in {unit}: ").strip()
#         try:
#             quantity = float(quantity_str)
#             if quantity <= 0:
#                 print("Quantity must be a positive number. Please try again.")
#             else:
#                 break
#         except ValueError:
#             print("Invalid quantity. Please enter a numeric value.")
# 
#     found_existing = False
#     for item in inventory:
#         if item.name.lower() == name.lower():
#             item.quantity += quantity
# 
#             if item.unit.lower() != unit.lower():
#                 print(
#                     f"Warning: Unit for '{name}' changed from "
#                     f"'{item.unit}' to '{unit}'."
#                 )
#                 item.unit = unit
#             print(
#                 f"Updated quantity for {item.name}: "
#                 f"new total is {item.quantity} {item.unit}."
#             )
#             found_existing = True
#             break
# 
#     if not found_existing:
#         new_ingredient = Ingredient(name, quantity, unit)
#         inventory.append(new_ingredient)
#         print(f"Added new ingredient: {new_ingredient}.")
#     print("-----------------------------")
# 
# 
# def get_ingredient_quantity(inventory, ingredient_name):
#     """
#     Returns the available quantity of an ingredient from the inventory.
# 
#     - Case-insensitive lookup on ingredient name.
#     - Returns the quantity as a float.
#     - Returns 0.0 if the ingredient is not found.
# 
#     This is written to satisfy the helper-function rubric (5/5).
#     """
#     target = ingredient_name.strip().lower()
#     for item in inventory:
#         if item.name.strip().lower() == target:
# 
#             return float(item.quantity)
#     return 0.0
# 
# 
# def check_recipe(inventory):
#     """
#     Lists recipes, asks the user to pick one, and checks stock.
# 
#     - Lists all recipes from RECIPES.
#     - Gets and validates user input (no crashes on bad input).
#     - Iterates through all required ingredients.
#     - For each ingredient, compares stock vs requirement.
#     - If any are short, raises InsufficientStockError with a clear,
#       specific message including missing quantities.
# 
#     The caller (e.g., main menu) should wrap this in a try/except
#     InsufficientStockError block for clean control flow.
#     """
#     if not RECIPES:
#         print("No recipes are defined.")
#         return
# 
# 
#     print("\n--- Available Recipes ---")
#     recipe_names = list(RECIPES.keys())
#     for idx, name in enumerate(recipe_names, start=1):
#         print(f"{idx}. {name}")
#     print("-------------------------")
# 
# 
#     while True:
#         choice = input(
#             f"Select a recipe by number (1-{len(recipe_names)}) "
#             "or 'q' to cancel: "
#         ).strip()
# 
#         if choice.lower() == 'q':
#             print("Recipe check cancelled.")
#             return
# 
#         try:
#             selection = int(choice)
#             if 1 <= selection <= len(recipe_names):
#                 break
#             else:
#                 print(
#                     f"Please enter a number between 1 and {len(recipe_names)}, "
#                     "or 'q' to cancel."
#                 )
#         except ValueError:
#             print(
#                 f"Invalid input. Please enter a number between 1 and "
#                 f"{len(recipe_names)}, or 'q' to cancel."
#             )
# 
#     selected_name = recipe_names[selection - 1]
#     required_ingredients = RECIPES[selected_name]
# 
# 
#     missing_details = []
# 
#     for ingredient_name, required_quantity in required_ingredients.items():
#         available_quantity = get_ingredient_quantity(inventory, ingredient_name)
# 
# 
#         if available_quantity < float(required_quantity):
#             shortage = float(required_quantity) - available_quantity
#             missing_details.append(
#                 f"{ingredient_name}: need {required_quantity}, "
#                 f"have {available_quantity:.2f}, missing {shortage:.2f}"
#             )
# 
# 
#     if missing_details:
#         message = (
#             f"Insufficient stock for recipe '{selected_name}'.\n"
#             "Missing ingredients:\n  " + "\n  ".join(missing_details)
#         )
#         raise InsufficientStockError(message)
# 
# 
#     print(f"You have enough ingredients to make '{selected_name}'.")
#

"""Q4"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile inventory_planner.py
# from ingredient_class import Ingredient
# from ingredient_class import Ingredient, InsufficientStockError, RECIPES
# 
# import csv
# from ingredient_class import Ingredient, InsufficientStockError, RECIPES
# 
# 
# def save_inventory(inventory):
#     """Saves the current inventory to a CSV file."""
#     with open('inventory.csv', 'w', newline='') as csvfile:
#         writer = csv.writer(csvfile)
# 
#         writer.writerow(["name", "quantity", "unit"])
#         for ingredient in inventory:
#             writer.writerow(ingredient.to_csv_row())
# 
# 
# def load_inventory():
#     """Loads inventory from a CSV file and returns a list of Ingredient objects.
# 
#     - Validates the CSV header.
#     - Merges duplicate ingredients by name (case-sensitive key).
#     """
#     inventory_map = {}
#     try:
#         with open('inventory.csv', 'r', newline='') as csvfile:
#             reader = csv.reader(csvfile)
#             headers = next(reader)
#             if headers != ["name", "quantity", "unit"]:
#                 raise ValueError(
#                     "Invalid CSV header. Expected ['name', 'quantity', 'unit']."
#                 )
# 
#             for row in reader:
#                 if len(row) != 3:
#                     print(f"Skipping malformed row: {row}")
#                     continue
#                 name, quantity_str, unit = row
#                 try:
#                     quantity = float(quantity_str)
#                     if name in inventory_map:
# 
#                         inventory_map[name].quantity += quantity
#                     else:
#                         inventory_map[name] = Ingredient(name, quantity, unit)
#                 except ValueError:
#                     print(
#                         f"Skipping row due to invalid quantity for {name}: "
#                         f"'{quantity_str}' is not numeric."
#                     )
#     except FileNotFoundError:
#         print("inventory.csv not found. Returning empty inventory.")
#         return []
#     except ValueError as e:
#         print(f"Error loading inventory: {e}")
#         return []
# 
#     return list(inventory_map.values())
# 
# 
# def view_inventory(inventory):
#     """Displays the current inventory."""
#     if not inventory:
#         print("Your inventory is currently empty.")
#         return
# 
#     print("\n--- Current Inventory ---")
#     for ingredient in inventory:
#         print(ingredient)
#     print("-------------------------")
# 
# 
# def add_ingredient(inventory):
#     """Adds a new ingredient or updates an existing one in the inventory."""
#     print("\n--- Add/Update Ingredient ---")
#     while True:
#         name = input("Enter ingredient name (e.g., 'Flour', 'Sugar'): ").strip()
#         if name:
#             break
#         else:
#             print("Ingredient name cannot be empty. Please try again.")
# 
#     while True:
#         unit = input(
#             f"Enter unit for {name} (e.g., 'grams', 'ml', 'pieces'): "
#         ).strip()
#         if unit:
#             break
#         else:
#             print("Unit cannot be empty. Please try again.")
# 
#     while True:
#         quantity_str = input(f"Enter quantity for {name} in {unit}: ").strip()
#         try:
#             quantity = float(quantity_str)
#             if quantity <= 0:
#                 print("Quantity must be a positive number. Please try again.")
#             else:
#                 break
#         except ValueError:
#             print("Invalid quantity. Please enter a numeric value.")
# 
#     found_existing = False
#     for item in inventory:
#         if item.name.lower() == name.lower():
#             item.quantity += quantity
# 
#             if item.unit.lower() != unit.lower():
#                 print(
#                     f"Warning: Unit for '{name}' changed from "
#                     f"'{item.unit}' to '{unit}'."
#                 )
#                 item.unit = unit
#             print(
#                 f"Updated quantity for {item.name}: "
#                 f"new total is {item.quantity} {item.unit}."
#             )
#             found_existing = True
#             break
# 
#     if not found_existing:
#         new_ingredient = Ingredient(name, quantity, unit)
#         inventory.append(new_ingredient)
#         print(f"Added new ingredient: {new_ingredient}.")
#     print("-----------------------------")
# 
# 
# def get_ingredient_quantity(inventory, ingredient_name):
#     """
#     Returns the available quantity of an ingredient from the inventory.
# 
#     - Case-insensitive lookup on ingredient name.
#     - Returns the quantity as a float.
#     - Returns 0.0 if the ingredient is not found.
# 
#     This is written to satisfy the helper-function rubric (5/5).
#     """
#     target = ingredient_name.strip().lower()
#     for item in inventory:
#         if item.name.strip().lower() == target:
# 
#             return float(item.quantity)
#     return 0.0
# 
# 
# def check_recipe(inventory):
#     """
#     Lists recipes, asks the user to pick one, and checks stock.
# 
#     - Lists all recipes from RECIPES.
#     - Gets and validates user input (no crashes on bad input).
#     - Iterates through all required ingredients.
#     - For each ingredient, compares stock vs requirement.
#     - If any are short, raises InsufficientStockError with a clear,
#       specific message including missing quantities.
# 
#     The caller (e.g., main menu) should wrap this in a try/except
#     InsufficientStockError block for clean control flow.
#     """
#     if not RECIPES:
#         print("No recipes are defined.")
#         return
# 
# 
#     print("\n--- Available Recipes ---")
#     recipe_names = list(RECIPES.keys())
#     for idx, name in enumerate(recipe_names, start=1):
#         print(f"{idx}. {name}")
#     print("-------------------------")
# 
# 
#     while True:
#         choice = input(
#             f"Select a recipe by number (1-{len(recipe_names)}) "
#             "or 'q' to cancel: "
#         ).strip()
# 
#         if choice.lower() == 'q':
#             print("Recipe check cancelled.")
#             return
# 
#         try:
#             selection = int(choice)
#             if 1 <= selection <= len(recipe_names):
#                 break
#             else:
#                 print(
#                     f"Please enter a number between 1 and {len(recipe_names)}, "
#                     "or 'q' to cancel."
#                 )
#         except ValueError:
#             print(
#                 f"Invalid input. Please enter a number between 1 and "
#                 f"{len(recipe_names)}, or 'q' to cancel."
#             )
# 
#     selected_name = recipe_names[selection - 1]
#     required_ingredients = RECIPES[selected_name]
# 
# 
#     missing_details = []
# 
#     for ingredient_name, required_quantity in required_ingredients.items():
#         available_quantity = get_ingredient_quantity(inventory, ingredient_name)
# 
# 
#         if available_quantity < float(required_quantity):
#             shortage = float(required_quantity) - available_quantity
#             missing_details.append(
#                 f"{ingredient_name}: need {required_quantity}, "
#                 f"have {available_quantity:.2f}, missing {shortage:.2f}"
#             )
# 
# 
#     if missing_details:
#         message = (
#             f"Insufficient stock for recipe '{selected_name}'.\n"
#             "Missing ingredients:\n  " + "\n  ".join(missing_details)
#         )
#         raise InsufficientStockError(message)
# 
# 
#     print(f"You have enough ingredients to make '{selected_name}'.")
# 
# 
# 
# def get_ingredient_quantity(inventory, ingredient_name):
#     """
#     Returns the available quantity of an ingredient from the inventory.
# 
#     - Case-insensitive lookup on ingredient name.
#     - Always returns a float.
#     - Returns 0.0 if the ingredient is not found.
#     """
#     target = ingredient_name.strip().lower()
#     for item in inventory:
#         if item.name.strip().lower() == target:
# 
#             return float(item.quantity)
#     return 0.0
# 
# 
# def check_recipe(inventory):
#     """
#     Checks if there are enough ingredients for a chosen recipe.
# 
#     Args:
#       inventory: list[Ingredient] to check against.
#     Returns:
#         None
#     """
#     if not RECIPES:
#         print("No recipes are defined.")
#         return
# 
# 
#     print("\nAvailable recipes:")
#     for name in RECIPES.keys():
#         print(f" - {name}")
# 
# 
#     user_input = input("Enter recipe name to check: ").strip()
#     selected_name = None
#     for name in RECIPES.keys():
#         if name.lower() == user_input.lower():
#             selected_name = name
#             break
# 
#     if selected_name is None:
#         print(" Recipe not found.")
#         return
# 
#     recipe_needed = RECIPES[selected_name]
# 
#     missing_details = []
# 
# 
#     for ingredient_name, required_quantity in recipe_needed.items():
#         required_quantity = float(required_quantity)
#         available_quantity = get_ingredient_quantity(inventory, ingredient_name)
# 
#         if available_quantity < required_quantity:
#             shortage = required_quantity - available_quantity
# 
# 
#             unit = ""
#             for item in inventory:
#                 if item.name.strip().lower() == ingredient_name.strip().lower():
#                     unit = item.unit
#                     break
# 
# 
#             if unit:
#                 detail = (
#                     f"{ingredient_name}: need {required_quantity:.2f} {unit}, "
#                     f"have {available_quantity:.2f} {unit}, "
#                     f"add {shortage:.2f} {unit}"
#                 )
#             else:
# 
#                 detail = (
#                     f"{ingredient_name}: need {required_quantity:.2f}, "
#                     f"have {available_quantity:.2f}, "
#                     f"add {shortage:.2f}"
#                 )
# 
#             missing_details.append(detail)
# 
# 
#     if missing_details:
#         message_lines = [
#             f"Insufficient stock for recipe '{selected_name}'.",
#             "Missing ingredients (suggested quantities to add):",
#         ]
#         message_lines.extend("  " + line for line in missing_details)
#         raise InsufficientStockError("\n".join(message_lines))
# 
# 
#     print(f" You have enough ingredients to make '{selected_name}'.")
#
